### ISSUE TITLE
sed Error when binding local nginx conf file

### ISSUE THREAD

**Issue by diridam** [Tob1as/docker-php#5]
Hi, 
When i'm binding a local nginx conf as default (in docker-compose.yaml):
`- ./nginx_default.conf:/etc/nginx/conf.d/default.conf:ro`

I get this error 
 sed: can't move '/etc/nginx/http.d/default.confnFPnpp' to '/etc/nginx/http.d/default.conf': Resource busy

i suppose there's something happening with the default.conf right in the moment entrypoint tries to inject things into the config files.
<img width="758" alt="image" src="https://user-images.githubusercontent.com/2481058/208201982-8020f7f0-ad4b-466b-ace1-5fd2ccd2efe4.png">

**Comment by Tob1as** [comment]
Hi,

i can reproduce it.

If you use env variables for nginx and a custom config it does not work with this:
`- ./nginx_default.conf:/etc/nginx/conf.d/default.conf:ro`
If you want to use your own config based on mine in the container, then create a subfolder (e.g. conf) and copy the config into it. In the docker-compose file then use (for complete folder):
`- ./conf:/etc/nginx/conf.d:rw`

**Comment by diridam** [comment]
Yes, binding the folder instead of only the file worked form me. Thanks
